---
- name: delete contents of cynccore folder
  shell: rm -rf /opt/cync_bbc/*

- name: Download the artifact from s3 bucket to the remote node
  aws_s3:
        bucket: "{{ bbcArtifactBucketName}}"
        object: "/cync/{{ bbcArtifactName }}"
        dest: /opt/cync_bbc/cync_bbc.tar.gz
        mode: get
- name: Extract the downloaded artifact
  unarchive:
    src: /opt/cync_bbc/cync_bbc.tar.gz
    dest: /opt/cync_bbc
    remote_src: yes

- name: Ensure directories are 0755
  command: find /opt/cync_bbc/ -type d -exec chmod 0755 * {} \;

- name: Ensure file  are 0644
  command: find /opt/cync_bbc/public/ -type f -exec chmod 0644 * {} \;

- name: delete the tar.gz file
  file:
    path: /opt/cync_bbc/cync_bbc.tar.gz
    state: absent
- name: Download the sidekiq god configuration file to the respective application folder
  aws_s3:
        bucket: "{{ configFileBucket }}"
        object: "unicorn_sidekiq.god"
        dest: /opt/cync_bbc/unicorn_sidekiq.god
        mode: get
#- name: Download the sidekiq yml configuration file to the respective application folder
   #aws_s3:
        #bucket: "{{ configFileBucket }}"
        #object: "sidekiq.yml"
        #dest: /opt/cync_bbc/config/sidekiq.yml
        #mode: get

- name: install gems
  command: bash -lc "cd /opt/cync_bbc && bundle install --local"
- name: Download the database configuration file to the respective application folder
  aws_s3:
        bucket: "{{ configFileBucket }}"
        object: "{{ databasefilename }}"
        dest: /opt/cync_bbc/config/database.yml
        mode: get
- name: Run DB migrations
  #when: inventory_hostname in groups['unicorn-hosts']
  command: bash -lc "cd /opt/cync_bbc && bundle exec rake db:migrate RAILS_ENV={{ envname }}"
- name: Ensure directories are 0755
  command: find /opt/cync_bbc/ -type d -exec chmod 0755 tmp {} \;
- name: Export rails environment
  command: bash -lc "cd /opt/cync_bbc && export RAILS_ENV={{ envname }}"
- name: Stop Sidekiq
 #when: inventory_hostname in groups['sidekiq-hosts'] or inventory_hostname in groups['sidekiq-similarity-hosts']
  command: bash -lc "cd /opt/cync_bbc && god terminate"
  ignore_errors: True
- name: Restart Sidekiq
  #when: inventory_hostname in groups['sidekiq-hosts'] or inventory_hostname in groups['sidekiq-similarity-hosts']
  command: bash -lc "cd /opt/cync_bbc && god -c unicorn_sidekiq.god RAILS_ENV={{ envname }}"
- name: Add Sidekiq restart to Crontab
  #when: inventory_hostname in groups['sidekiq-hosts'] or inventory_hostname in groups['sidekiq-similarity-hosts']
  cron:
    name: Sidekiq restart Crontab
    special_time: reboot
    job: "/bin/bash -l -c 'cd /opt/cync_bbc && god -c unicorn_sidekiq.god RAILS_ENV={{ envname }}' "


