---
- name: delete contents of opt/cash-application-angular directory
  shell: "rm -rf {{cashangularPath}}/*"

- name: create angular_cashapp_env directory example
  file:
    path: ~/angular_cashapp_env
    state: directory
    mode: 0755

- name: download the artifact from s3 bucket
  aws_s3:
    bucket: "{{ AngularCashArtifactBucketName }}"
    object: "/cashapp/{{ AngularCashArtifactName }}"
    dest: "{{cashangularPath}}/cash_application_angular.tar.gz"  
    mode: get

- name: Download the environment configuration file from s3 bucket
  aws_s3:
        bucket: "{{ configureBucketName }}"
        object: /ca-env.json
        dest: ~/angular_cashapp_env/ca-env.json
        mode: get

- name: Extract angular build
  unarchive:
    src: "{{cashangularPath}}/cash_application_angular.tar.gz"  
    dest: "{{cashangularPath}}" 
    remote_src: yes

- name: Ensure directories are 0755
  command: find "{{cashangularPath}}"/assets -type d -exec chmod 0755 {} \;

- name: Ensure files are 0644
  command: find "{{cashangularPath}}"/ -type f -exec chmod 0644 * {} \;


#- name: copy the configuration file to respective application folder
#  copy:
#    src: ~/angular_cashapp_env/ca-env.json
#    dest: /opt/cash-application-angular/assets/environment/env.json 
#    remote_src: yes

- name: delete the tar.gz file
  file:
    path: "{{cashangularPath}}/cash_application_angular.tar.gz"  
    state: absent

