---
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  roles:
    - { role: ../roles/send-sns-notification, status: started }

- hosts: jumphost
  connection: local
  remote_user: ubuntu
  tasks:
  - name: Block to copy ROR FactoringApp artifacts
    block:
    - include_role:
        name: ../roles/copyfactoringapp
    #ignore_errors: true
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed to copy ror FactoringApp artifacts
      - fail:
          msg: 'Copy ROR FactoringApp Artifacts failed'

- hosts: factoring-hosts
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block for ROR-FactoringApp deployment
    block:
    - include_role:
        name: ../roles/ror-factoringapp
    #ignore_errors: true
    rescue:
      - set_fact:
          statusMessage: "failed"


- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block to send ror factoringapp deployment failure notification
    block:
    - include_role:
        name: ../roles/send-sns-notification
      vars:
        status: failed ror factoringapp deployment
      with_items: "{{ groups['factoring-hosts'] }}"
      when: hostvars[item].statusMessage == "failed"

  - name: End the play if deployment fails
    block:
    - fail: msg="ROR factoringapp deployment failed"
      with_items: "{{ groups['factoring-hosts'] }}"
      when: hostvars[item].statusMessage == "failed"

  - name: Block to create AMI, LC and ASG
    block:
    - include_role:
       name: ../roles/create-ami-lc-updateasg
      with_items: "{{ ami_FactoringApp_tags }}"
    #ignore_errors: true
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed creating ami
      - fail:
          msg: 'Failed to create the AMI/LC/ASG'

- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  roles:
    - role: ../roles/send-sns-notification
      status: success

