---
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block to check the backup counts
    block:
    - include_role:
        name: ../roles/get-ami-snpshot-lc-count
    rescue:
    - include_role:
        name: ../roles/send-sns-notification
      vars:
        status: Backup count error!
    - fail:
        msg: 'Failed due to the backup count error!'

- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  roles:
    - { role: ../roles/send-sns-notification, status: started }

#- hosts: angular-hosts
#  gather_facts: false
#  remote_user: root
#  tasks:
#  - name: Block to copy maintenance window page
#    block:
#    - include_role:
#        name: ../roles/copy-maintenance-window
#    rescue:
#      - set_fact:
#          statusMessage: "failed"

#  - name: End the play if maintenance page copy fails.
#    block:
#    - fail: msg="Deployment failed while copying maintenance window page."
#      with_items: "{{ groups['angular-hosts'] }}"
#      when: hostvars[item].statusMessage == "failed"
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block to put uptimerobot maintainance
    block:
    - include_role:
        name: ../roles/put-uptime-robot-mwindow
      vars:
        app_name: "Base-RoR"         
    rescue:
    - include_role:
        name: ../roles/send-sns-notification
      vars:
        status: Putting MWindow on Uptimerobot failed!
    - fail:
        msg: 'Putting MWindow on Uptimerobot failed!'

- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: running sh files test
    block:
    - name: cloudwatch rule disable
      when: cloud_watch_rule_name_lists is defined
      script: cloudwatch_enable_disable.sh "disable" "{{cloud_watch_rule_name_lists}}"
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed disable cloud watch rule
      - fail:
          msg: 'failed disable cloud watch rule'

- hosts: jumphost
  #become: yes
  gather_facts: False
  connection: local
  remote_user: ubuntu
  tasks:
  - ec2_instance_facts:
      region: "{{ regionname }}"
      filters:
        "tag:Name": "{{cronTag }}"
    register: tagged_instances

- hosts: jumphost
  #become: yes
  gather_facts: False
  remote_user: ubuntu
  tasks:
  - name: Block to start the cron instance
    block:
    - name: start cron instance
      when: cronTag is defined and tagged_instances.instances[0].state.name == "stopped"
      local_action:
        module: ec2
        region: '{{ regionname }}'
        instance_tags:
          Name: "{{ cronTag }}"
        state: running
        wait: True
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed to starting cron instance
      - fail:
          msg: 'Failed to starting cron instance'
  - name: set fact value
    set_fact:
      ansible_started_cron_server: true
    when: cronTag is defined and tagged_instances.instances[0].state.name == "stopped"

- hosts: jumphost
  #become: yes
  gather_facts: False
  connection: local
  remote_user: ubuntu
  tasks:
  - ec2_instance_info:
      region: '{{ regionname }}'
      filters:
        "tag:Name": "{{ sidekiqSimilarityTag }}"
        "instance-state-name": ["stopped"]
    register: sidekiq_similarities_instances_output
    when: sidekiqSimilarityTag is defined

  - debug:
      msg: "sidekiqsimilary instances list {{sidekiq_similarities_instances_output.instances|map(attribute='instance_id')|list}}"
    when: sidekiqSimilarityTag is defined and sidekiq_similarities_instances_output.instances is defined

- hosts: jumphost
  #become: yes
  gather_facts: False
  remote_user: ubuntu
  tasks:
  - name: Block to start the similarity instance
    block:
    - name: start sidekiqsimilarity instance
      when: sidekiqSimilarityTag is defined and sidekiq_similarities_instances_output.instances is defined and sidekiq_similarities_instances_output.instances|map(attribute='instance_id')|list|length > 0
      local_action:
        module: ec2
        region: '{{ regionname }}'
        instance_ids: "{{sidekiq_similarities_instances_output.instances|map(attribute='instance_id')|list}}"
        state: running
        wait: True
    #ignore_errors: true
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed starting similarity instance
      - fail:
          msg: 'failed starting similarity instance'

  - name: Refresh inventory to ensure new instances exist in inventory # this is added for cc-828-Deployment not happened in Sidekiqsimilarity instance through Ansible Playbooks
    meta: refresh_inventory

  - pause:
      seconds: 30
    #when: sidekiq_similarities_instances_output.instances is defined and sidekiq_similarities_instances_output.instances|map(attribute='instance_id')|list|length > 0

- hosts: ror-hosts
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block for ROR deployment
    block:
    - include_role:
        name: ../roles/ror
    #ignore_errors: true
    rescue:
      - set_fact:
          statusMessage: "failed"

#- hosts: angular-hosts
#  gather_facts: false
#  remote_user: root
#  tasks:
#  - name: Block to remove maintenance window page
#    block:
#    - include_role:
#        name: ../roles/remove-maintenance-window
#    rescue:
#      - set_fact:
#          statusMessage: "failed"

#  - name: End the play if maintenance page removal fails.
#    block:
#    - fail: msg="Deployment failed while deleting maintenance window page."
#      with_items: "{{ groups['angular-hosts'] }}"
#      when: hostvars[item].statusMessage == "failed"

- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: Block to send ror deployment failure notification
    block:
    - include_role:
        name: ../roles/send-sns-notification
      vars:
        status: failed ror deployment
      with_items: "{{ groups['ror-hosts'] }}"
      when: hostvars[item].statusMessage == "failed"

  - name: End the play if deployment fails
    block:
    - fail: msg="ROR deployment failed"
      with_items: "{{ groups['ror-hosts'] }}"
      when: hostvars[item].statusMessage == "failed"

  - name: Block to create AMI, LC and ASG
    block:
    - include_role:
       name: ../roles/create-ami-lc-updateasg
      with_items: "{{ ami_tags }}"
    #ignore_errors: true
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed creating ami
      - fail:
          msg: 'Failed to create the AMI/LC/ASG'

  - name: Block to stop similarity instance
    block:
    - name: Stop the similarity instance
      when: sidekiqSimilarityTag is defined
      local_action:
        module: ec2
        region: '{{ regionname }}'
        instance_tags:
          Name: "{{ sidekiqSimilarityTag }}"
        state: stopped
        wait: False
    #ignore_errors: true
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed to stop similarity instance
      - fail:
          msg: 'Failed to stop similarity instance'
- hosts: jumphost
  #become: yes
  gather_facts: False
  remote_user: ubuntu
  tasks:
  - name: Block to stop the cron instance
    block:
    - name: stop cron instance
      when: cronTag is defined and ansible_started_cron_server is defined
      local_action:
        module: ec2
        region: '{{ regionname }}'
        instance_tags:
          Name: "{{ cronTag }}"
        state: stopped
        wait: False
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed to stop cron instance
      - fail:
          msg: 'Failed to stop cron instance'    
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: running sh files test
    block:
    - name: cloudwatch rule enable
      when: cloud_watch_rule_name_lists is defined
      script: cloudwatch_enable_disable.sh "enable" "{{cloud_watch_rule_name_lists}}"
    rescue:      
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: failed enable cloud watch rule
      - fail:
          msg: 'failed enable cloud watch rule'
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  tasks:
  - name: QA Automation Application List
    when: qa_automation_trigger_required == "true"
    block:
    - include_role:
        name: ../roles/ssm
      with_items: "{{ qa_automation_trigger_application_list }}"
    rescue:
      - include_role:
          name: ../roles/send-sns-notification
        vars:
          status: QA Automation Trigger Application List
      - fail:
          msg: 'Failed QA Automation Trigger Application List'
- hosts: jumphost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  roles:
    - role: ../roles/send-sns-notification
      status: success
